### ISSUE TITLE
Applicability of OpenDust in PLASMA flow control

### ISSUE THREAD

**Issue by Badtreater** [kolotinsky1998/opendust#1]
**Dear developers,** 
thank you so much for providing the open-source PLASMA simulation codes. It is my honor to write this letter to you guys who are expanding into new fields. I am a novice in PLASMA research and working hard to complete my doctoral studies.However, due to my poor ability on programming of finite element solvers, it has been hard to complete the simulation code of PLASMA completely on my own. To be honest, I was very excited when I first saw OpenDust. I thought it might help me to supplement my lack of simulation.
To get back to the point, I hope to use OpenDust to complete the simulation work in the literature[1], but unfortunately, due to a lack of understanding of the underlying solver, I am unable to make a judgment on whether OpenDust can correctly complete this simulation process. I am eager to receive your answers on the applicability of the OpenDust underlying solver to the simulation of PLASMA flow control actuators. If the work can proceed, I also hope to include the reference of OpenDust in my own paper when publishing articles in the future. Thank you so much. 

Reference
[1]Kunwar Pal Singh, Subrata Roy; Modeling plasma actuators with air chemistry for effective flow control. Journal of Applied Physics 15 June 2007; 101 (12): 123308. https://doi.org/10.1063/1.2749467

**Comment by kolotinsky1998** [comment]
Thank you for your interest to the OpenDust code!

Equations which are being solved to simulate plasma in [1] are continuous drift-diffusion equations both for electrons and different ion types coupled with chemical reactions and Poisson’s equation.

OpenDust is developed to simulate ion dynamics in a plasma flow around microparticles of condensed matter, so called dust particle in complex plasma physics. Electrons are considered to act as a Boltzmann fluid, and ion dynamics is governed with the molecular dynamics approach. Currently, the OpenDust can simulate only one type of ions and possibility to simulate chemical reaction is not implemented. For those reasons, I am not sure you can use OpenDust to reproduce simulation results from [1].

There are some open-source packages which enable users to translate scientific models into efficient finite element code https://fenicsproject.org/, https://mfem.org/. May be you can use them for your task.

Good luck in your research!

**Comment by Badtreater** [comment]
Thank you very much for your explanation of the research in the article, which helped me better understand this issue. You are the researcher who has provided me with the most detailed explanation so far. Thank you very much. If you don't mind the trouble, I hope to give you a little tip or gift as a thank you. I'm not sure if I can keep in touch in the future. I would like to ask for your advice and thank you.

| |
Tayir
|
|
***@***.***
|
On 7/2/2023 16:30，Daniil ***@***.***> wrote：

Thank you for your interest to the OpenDust code!

Equations which are being solved to simulate plasma in [1] are continuous drift-diffusion equations both for electrons and different ion types coupled with chemical reactions and Poisson’s equation.

OpenDust is developed to simulate ion dynamics in a plasma flow around microparticles of condensed matter, so called dust particle in complex plasma physics. Electrons are considered to act as a Boltzmann fluid, and ion dynamics is governed with the molecular dynamics approach. Currently, the OpenDust can simulate only one type of ions and possibility to simulate chemical reaction is not implemented. For those reasons, I am not sure you can use OpenDust to reproduce simulation results from [1].

There are some open-source packages which enable users to translate scientific models into efficient finite element code https://fenicsproject.org/, https://mfem.org/. May be you can use them for your task.

Good luck in your research!

**Comment by kolotinsky1998** [comment]
Glad to help you

**Comment by Badtreater** [comment]
Thank you !


| |
Tayir
|
|
***@***.***
|
On 7/2/2023 21:50，Daniil ***@***.***> wrote：

Glad to help you
